version: '3.8'

services:
  astro-static:
    build:
      context: .
    ports:
      - "8090:80"
    restart: always
    networks:
      - app-network
      - red-compartida

networks:
  app-network:
    driver: bridge
  red-compartida:
    external: true

